name: CI

on:
  push:
    branches:
      - 'master'
      - 'docs-generation'
    tags-ignore:
      - '*.*'

jobs:
  test:
    name: "phpDocumentor"
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      - name: Check out code into the workspace
        if: success()
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Cache phpDocumentor
        id: cache-phpdocumentor
        uses: actions/cache@v2
        with:
          path: phpDocumentor.phar
          key: phpdocumentor
      - name: Download latest phpDocumentor
        if: steps.cache-phpdocumentor.outputs.cache-hit != 'true'
        run: curl -O -L https://phpdoc.org/phpDocumentor.phar
      - name: Generate documentation
        run: php phpDocumentor.phar -d src -t docs
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Deploy documentation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
